package com.nasnav.models.data_process;

public enum ColumnEnum {

    QUANTITY("DOUBLE"),
    VARIANT_ID("STRING"),
    PRICE("DOUBLE"),
    DESCRIPTION("STRING"),
    DISCOUNT("DOUBLE"),
    EXTERNAL_ID("STRING"),
    PRODUCT_GROUP_KEY("STRING"),
    PRODUCT_NAME("STRING"),
    BAR_CODE("STRING"),
    BRAND("STRING"),
    TAGS("STRING"),
    CLASS("STRING"),
    COLOR("STRING"),
    SIZE("STRING"),
    CUT("STRING"),
    GLAZE("STRING"),
    INFO("STRING"),
    ORIGIN("STRING"),
    PRODUCT("STRING"),
    CODE("STRING"),
    STYLE("STRING"),
    TEXTURE("STRING"),
    TYPE("STRING"),
    LENGTH("DOUBLE"),
    LEVIS_CODE("STRING"),
    LOOKUP_CODE("STRING"),
    ITEM_CODE("STRING"),
    BY_MODEL("STRING"),
    STYLE_NAME("STRING"),
    COLOR_FAMILY("STRING"),
    DIVISION("STRING"),
    GENDER("STRING"),
    CATEGORY("STRING"),
    CLASS_HIERARCHY("STRING"),
    FIT_NAME("STRING"),
    SUB_CLASS_HIERARCHY("STRING"),
    LEG_OPENING("STRING"),
    CLOSURE("STRING"),
    POCKET_STYLING("STRING"),
    MISC_FEATURES_BENEFITS("STRING"),
    WASH_INSTRUCTIONS("STRING"),
    CLASS_HIERARCHY2("STRING"),
    SUB_CLASS_HIERARCHY2("STRING"),
    SEASONALITY("STRING"),
    EAN_CODE("STRING"),
    FABRICATION("STRING"),
    LEVIS_COLLABORATION("STRING"),
    IMAGE("STRING"),
    LINK("STRING"),
    IN_STORE("STRING"),
    REMARKS("STRING"),
    ACTION("STRING"),
    ARTICLE_NO("STRING"),
    FAMILY("STRING"),
    ART_NAME("STRING"),
    SEASON("STRING"),
    PRODUCT_GROUP("STRING"),
    PRODUCT_TYPE("STRING"),
    SUB_GENDER("STRING"),
    SEX("STRING"),
    RTP("STRING");

    private final String dataType;

    ColumnEnum(String dataType) {
        this.dataType = dataType;
    }

    public String getDataType() {
        return dataType;
    }
}
